### PR TITLE
Depend on the 'yii\web\JqueryAsset'

### PR DESCRIPTION
**Pull request by thiagotalma**
Fix an error ensuring that the js file is never included before jQuery.

(You need to evaluate this dependence in all of their assets that depend on jQuery)

### CODE REVIEW

**Comment by samuelroxo** [comment]
@kartik-v please, accept this request, this issue is becoming annoying.

**Comment by uagrace** [comment]
+1

**Comment by kartik-v** [comment]
Actually this may not entirely be the correct way to fix it... will try to check and update.

This is because the `DateRangePickerAsset` extends `kartik\base\AssetBundle` and the `kartik\base\AssetBundle` already depends on JqueryAsset. 

So the depends property must not be overwritten...

**Comment by samuelroxo** [comment]
Thank you @kartik-v, you're the great.

**Pull request closed without merging**
